#  <center> Numpy

- **Numpy = Numeric Python** <br>
<br>
- Pros
    - Calculations over entire arrays
    - Easy
    - Fast 
- Cons
    - contain only one type 

## Installition
`pip3 install numpy`

## Example

In [4]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
print(height)
print(weight)

[1.73, 1.68, 1.71, 1.89, 1.79]
[65.4, 59.2, 63.6, 88.4, 68.7]


`weight / height ** 2` 

---------------------------------------------------------------------------
TypeError            Traceback (most recent call last) <br>
Cell In[2], line 1 <br>
----> 1 weight / height ** 2 <br>
<br>
TypeError: unsupported operand type(s) for ** or pow(): 'list' <br>
and 'int'<br>

In [5]:
import numpy as np

np_height = np.array(height)
np_weight = np.array(weight)

print(np_height)
print(np_weight)

[1.73 1.68 1.71 1.89 1.79]
[65.4 59.2 63.6 88.4 68.7]


In [4]:
bmi = np_weight / np_height ** 2
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [6]:
np.array([1.0, "is", True])

array(['1.0', 'is', 'True'], dtype='<U32')

The array will be all of string <br>
= Numpy contain only one type

In [6]:
python_list = [1,2,3]
numpy_array = np.array([1,2,3])

print(f' Sum of two Python lists are {python_list + python_list}')
print(f'Sum of two Numpy arrays are {numpy_array + numpy_array}')

 Sum of two Python lists are [1, 2, 3, 1, 2, 3]
Sum of two Numpy arrays are [2 4 6]


!!! Diffrent types: diffrent behavior

In [7]:
bmi[1]

np.float64(20.97505668934241)

In [8]:
bmi > 23

array([False, False, False,  True, False])

In [9]:
bmi[bmi > 23]

array([24.7473475])

## Type of NumPy Arrays 

In [12]:
type(np_height)

numpy.ndarray

In [11]:
type(np_weight)

numpy.ndarray

n-dimensional array

## 2D Arrays

In [7]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                  [65.4, 59.2, 63.6, 88.4, 68.7]])
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [15]:
np_2d.shape

(2, 5)

2 rows, 5 columns

In [17]:
np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
          [65.4, 59.2, 63.6, 88.4, "68.7"]])

array([['1.73', '1.68', '1.71', '1.89', '1.79'],
       ['65.4', '59.2', '63.6', '88.4', '68.7']], dtype='<U32')

If one of them is string, it effects on all the array

In [8]:
np_2d[0]

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [23]:
print(np_2d[0][2])

1.71


In [22]:
print(np_2d[0,2])

1.71


In [26]:
np_2d[:,1:3]

array([[ 1.68,  1.71],
       [59.2 , 63.6 ]])

In [29]:
np_2d[1,:]

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [10]:
np_2d[:,0]

array([ 1.73, 65.4 ])

In [9]:
np.mean(np_2d[:,0])

np.float64(33.565000000000005)

In [11]:
np.median(np_2d[:,0])

np.float64(33.565000000000005)

- `np.corrcoef()`
- `np.std()`
- `sum()`
- `sort()`

### Generate Data
- Arguments for `np.random.normal()`:
    - distrubution mean
    - distribution stasndard deviation
    - number of samples

In [ ]:
height = np.round(np.random.normal(1.75, 0.20, 5000), 2)
weight = np.random.normal(60.32, 15, 5000, 2)